{% set name = "ppci" %}
{% set version = "0.5.6" %}
{% set sha256 = "d64c169529e039a7968a95c4dfc25cd7768e6629b8dc576df5e291c9f942660e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [py2k]
  number: 1000
  entry_points:
    - ppci-asm = ppci.cli.asm:asm
    - ppci-build = ppci.cli.build:build
    - ppci-c3c = ppci.cli.c3c:c3c
    - ppci-cc = ppci.cli.cc:cc
    - ppci-dbg = ppci.cli.dbg:dbg
    - ppci-disasm = ppci.cli.disasm:disasm
    - ppci-hexutil = ppci.cli.hexutil:hexutil
    - ppci-ld = ppci.cli.link:link
    - ppci-llc = ppci.cli.llc:llc
    - ppci-mkuimage = ppci.cli.mkuimage:mkuimage
    - ppci-objcopy = ppci.cli.objcopy:objcopy
    - ppci-objdump = ppci.cli.objdump:objdump
    - ppci-opt = ppci.cli.opt:opt
    - ppci-pascal = ppci.cli.pascal:pascal
    - ppci-pedump = ppci.cli.pedump:pedump
    - ppci-pycompile = ppci.cli.pycompile:pycompile
    - ppci-readelf = ppci.cli.readelf:readelf
    - ppci-wasm2wat = ppci.cli.wasm2wat:wasm2wat
    - ppci-wasmcompile = ppci.cli.wasmcompile:wasmcompile
    - ppci-wat2wasm = ppci.cli.wat2wasm:wat2wasm
    - ppci-wabt = ppci.cli.wabt:wabt
    - ppci-yacc = ppci.cli.yacc:yacc
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - colorama

test:
  imports:
    - ppci
    - ppci.arch
    - ppci.binutils
    - ppci.build
    - ppci.cli
    - ppci.codegen
    - ppci.lang
    - ppci.lang.c
    - ppci.lang.c3
    - ppci.lang.python
    - ppci.opt
    - ppci.utils
  commands:
    - ppci-asm --help
    - ppci-build --help
    - ppci-c3c --help
    - ppci-cc --help
    - ppci-dbg --help
    - ppci-disasm --help
    - ppci-hexutil --help
    - ppci-ld --help
    - ppci-llc --help
    - ppci-mkuimage --help
    - ppci-objcopy --help
    - ppci-objdump --help
    - ppci-opt --help
    - ppci-pascal --help
    - ppci-pedump --help
    - ppci-pycompile --help
    - ppci-wasm2wat --help
    - ppci-wasmcompile --help
    - ppci-yacc --help

about:
  home: http://ppci.readthedocs.io/
  license: BSD-2-Clause
  license_file: 'license.txt'
  summary: 'A compiler for ARM, X86, MSP430, xtensa and more implemented in pure Python'
  doc_url: http://ppci.readthedocs.io/
  dev_url: https://bitbucket.org/windel/ppci

extra:
  recipe-maintainers:
    - windelbouwman
    - almarklein
