travis:
  secure:
    BINSTAR_TOKEN: hmBe0K0UrtTfHtBpsFsT20l6d8ytYdC3qTFk+K1PAJ5j7tEm/12gAtxze1iECd9hmozsPTpTQQ3qZAo5q3RUBzyLakoGo/8PgZT/R/JOFjF1S3XhlxkL32nXTW6rLV4xFjuQr9nnVRkB/ltNA8gRD2xPanl6kHIh0krb7tC/IJoiN0f0VmOgbI3obIYE35+PsFq4xz1JGfS/D2wqc0roRRhLIBsKmx3ihLIo5/7QEHWCUmDwuU9p+SJuIA22Y4a/S/40TEEcK7jY9vVCyVBdzV6WjNrjEd+aHg1fky093aw/cv8YbUwshih3zAtRmVZzATqgx1Bh9zy1Mn6K7kSDRSH6II/YPnWzGFClp7AD9vtmacUVUeNXYoQjQ+U0HFenViUq+L5xi0zfjhPTcJY0ZdkwN7LN3kHM2TLjwkgXCktcnP7gyVv1ZtJzQJQI8FuLfItR0LtUS8oWETR+3nBpolMeJFt6eMtot3EDjcBW+dXcTgc+zZoJtSZavYd+37Q6m+oIgu98B77rasq4ND6DiGeKOe4stXi3qyml2BlNjGBRiSbOk7D48xyrLU2XNNeCSWfcAWqJqdJ9pnaDGKr83qg5HpRp3sqzTV7pb0Dxjeb7OHHWHmAUXZJnoVrj3VkM9fThj7fPGJcifuuVLB3p6sUEyGnZavi+t6qH7UdSizM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
