appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: lOeQ/Ze5kJD0jElNZrUEwbsyqok4Ind7QIw+ZgsnumKdxfZ8pNolDJ9oPCPSW/mZFeywSLK6u2rHHWGw9piUW1r2x+nZP+7IhC2JB6pxPVK5CQjuIxWDHik989ySGZbExmE4m/ng+i1PYyRt4zRFEsexlhYbKVkigEw82WYnJAjJft7JyR3Rx2kT1G4EVpAHzdLYCG/GcMYnyI2c6F3P60Qsy8RUDyPc3FDJNF1+i/S5awVBiDljLAHXZE0PPF5DV4YS7sbHfiZ5MfdcKG5QgwbwpCS4H4zf3Dolo3lO5OvqL31jmcmyKlzUuTRjIYgHgVyx8YaZK9Dtc7cCMPsiIWUKYnEo85D3BxnMQNVseYwPyYxNrXF+blre75SsUyhi3ophvBFYEIG0OMvMotlowKs6FNWlsAR7KsgJ41AdX6mi0t3gj6LOGcySrdHJ+OyqHj2oRkIdGpZQyaZ9QAXeGVIYIqi81p6GulOQKOQpFtHFVN2kRvjexJiIBaaQiAXeCOOXEiQzC+yW2Rrf0pZ8cGL4CX9JQf5gPAAjYY8Ec9QYPyX+bJNgzOYsjTgRZc60z1OGYKc/ahR0uxRF9NN6fBbaACvdErbfVO5Qj30d8/qhloUK3eeoTMgDCsSTSTUKZub7GWwwnYtuJo9zkefOEsOuojIMHN7B/lIkgSOpaws=}
